import { useEffect } from "react";
import { initMercadoPago, CardPayment } from "@mercadopago/sdk-react";

interface Props {
  publicKey: string;
  onToken: (cardTokenId: string) => void;
}

/**
 * Card Payment Brick tokenization component.
 * Initialises the @mercadopago/sdk-react instance, renders the hosted Brick,
 * and extracts the card token from the Brick's onSubmit payload.
 *
 * onToken is called with the card_token_id — no payment is triggered from the
 * frontend. The token is passed to the A.2 creation flow immediately after.
 */
export function CardBrick({ publicKey, onToken }: Props) {
  useEffect(() => {
    // initMercadoPago is idempotent — safe to call on every mount
    initMercadoPago(publicKey, { locale: "es-AR" });
  }, [publicKey]);

  return (
    <CardPayment
      initialization={{ amount: 1 }}
      onSubmit={async (formData) => {
        // formData.token is the card token id generated by the Brick
        if (formData.token) {
          onToken(formData.token);
        }
      }}
      onError={(err) => {
        console.error("[CardBrick] error:", err);
      }}
      customization={{
        visual: { hidePaymentButton: false },
        paymentMethods: {
          maxInstallments: 1,
        },
      }}
    />
  );
}
