import { useState, useEffect } from "react";
import { initMercadoPago, CardPayment } from "@mercadopago/sdk-react";

interface Props {
  publicKey: string;
  onToken: (cardTokenId: string) => void;
}

/**
 * Card Payment Brick tokenization component.
 * Initialises the @mercadopago/sdk-react instance, renders the hosted Brick,
 * and extracts the card token from the Brick's onSubmit payload.
 *
 * onToken is called with the card_token_id — no payment is triggered from the
 * frontend. The token is passed to the A.2 creation flow immediately after.
 */
export function CardBrick({ publicKey, onToken }: Props) {
  const [submitError, setSubmitError] = useState<string | null>(null);

  useEffect(() => {
    // initMercadoPago is idempotent — safe to call on every mount
    initMercadoPago(publicKey, { locale: "es-AR" });
  }, [publicKey]);

  return (
    <div>
      <CardPayment
        initialization={{ amount: 1 }}
        onSubmit={async (formData) => {
          // formData.token is the card token id generated by the Brick
          if (formData.token) {
            setSubmitError(null);
            onToken(formData.token);
          } else {
            const msg = "Brick did not return a card token — please retry.";
            console.error("[CardBrick] onSubmit: missing token", formData);
            setSubmitError(msg);
          }
        }}
        onError={(err) => {
          console.error("[CardBrick] error:", err);
        }}
        customization={{
          visual: { hidePaymentButton: false },
          paymentMethods: {
            maxInstallments: 1,
          },
        }}
      />
      {submitError && (
        <p className="mt-2 text-xs text-red-600 bg-red-50 border border-red-200 rounded px-3 py-2">
          {submitError}
        </p>
      )}
    </div>
  );
}
